grafana:
  enabled: false
alertmanager:
  enabled: false # Optional: disable if you don't need alerting yet

# 2. Configure Prometheus to look for ServiceMonitors from other namespaces
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    
    # Optional: Set retention
    retention: 1d

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false