---
env:
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  GF_AUTH_DISABLE_LOGIN_FORM: true

nameOverride: tempo

tempo:
  reportingEnabled: false 
  retention: 3h 
  metricsGenerator:
    enabled: true
