name: demok-docker

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel/otel-config.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - demok-docker

  grafana:
    image: grafana/grafana:11.3.0-security-01
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - demok-docker

  loki:
    image: grafana/loki:3.4.3
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yaml
    networks:
      - demok-docker

  tempo:
    image: grafana/tempo:2.8.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200"
      - "4317"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - demok-docker

networks:
  demok-docker:
    name: demok-docker